apiVersion: witboost.com/v1
kind: EditTemplate
metadata:
  name: edit-azure-storage-adlsgen2-template.1
  title: Edit ADLS Gen2 Storage Area
  description: Edit ADLS Gen2 Storage Area of a Data Product
  tags:
    - edit
    - azure
    - adls
    - storage
spec:
  owner: agile_lab
  useCaseTemplateId:
    - urn:dmb:utm:azure-storage-adlsgen2-template:0.0.0
  parameters:
    - title: Update ADLS Gen2 Storage Area
      description: |
        This wizard will allow you to edit the metadata for a previously created ADLS Gen2 Storage Area.
        Most metadata is editable but some (like the name, domain, dataproduct etc.) are not; these fields will be read-only.
        Some of the files in the component's repository cannot be updated by this wizard, namely:
          - Documentation: `README.md`, `docs/index.md` etc.
          - CI/CD: `.gitlab-ci.yml`
        You need to take care of updating these yourself, as given their nature it's hard to do automatically and they are often edited manually after the component's creation.

    - title: Update Component Metadata
      description: Update Basic Information for this component.
      required:
        - description
      properties:
        name:
          title: Name
          type: string
          description: Not editable. The name of the component.
          ui:disabled: true
        fullyQualifiedName:
          title: Fully Qualified Name
          type: string
          description: Fully Qualified Name of the component.
        description:
          title: Description
          type: string
          description: Required. Help others understand what this component is for. What data will it contain?
        domain:
          title: Domain
          type: string
          description: Not editable. Domain of the Data Product this component belongs to
          ui:field: EntityPicker
          ui:disabled: true
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - Domain
        dataproduct:
          title: Data Product
          type: string
          description: Not editable. Data Product this component belongs to
          ui:field: EntityPicker
          ui:filter:
            - fieldName: domain
              entityPath: spec.domain
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - System
          ui:disabled: true
        identifier:
          title: Identifier
          type: string
          description: Autogenerated from the information above. A unique identifier for the component. It will not be editable after creation and is a string composed of [a-zA-Z] separated by any of [-_].
          ui:field: ComponentIdentifierPicker
          ui:options:
            allowArbitraryValues: false
        developmentGroup:
          title: Development Group
          type: string
          description: Automatically selected from the Data Product metadata. Data Product development group.
          ui:field: EntitySelectionPicker
          ui:fieldName: dataproduct
          ui:property: spec.owner
          ui:options:
            allowArbitraryValues: false
        dependsOn:
          title: Dependencies
          type: array
          description: |
            A component could depend on other components in the same Data Product. This information will be used to deploy the components in such an order that their dependencies already exist.
            **Warning**: be careful not to select this component as its own dependency, otherwise it will become undeployable until you edit it again and remove that circular dependency.
          default: []
          items:
            type: string
            ui:field: EntityComponentsPicker
            ui:fieldName: dataproduct
            ui:options:
              allowArbitraryValues: false
        tags:
          title: Tags
          type: array
          description: Tags for the component
          default: []
          items:
            type: string

    - title: Update ADLS Gen2 Storage Area Deployment Information
      description: Update deployment information for the ADLS Gen2 Storage Area
      properties:
        resourceGroup:
          title: Resource Group
          type: string
          description: |
            Not editable. The Resource Group to assign the Storage Account to. IT SHOULD ALREADY EXIST.
          ui:disabled: true
        storageAccount:
          title: Storage Account
          type: string
          description: |
            Not editable. A name for the storage account where to create the ADLSgen2 container.
            If not existing, it will be created. The name must be unique across all existing storage account names in Azure.
          ui:disabled: true
        containers:
          title: Containers
          type: array
          default: []
          description: Required. The ADLS Gen2 container(s) to create inside the storage account.
          minItems: 1
          items:
            type: string
            title: Name of the Container
            description: Name of the container.
            minLength: 3
            maxLength: 63
            ui:field: RegexPicker # Not currently enforced.
            validation:
              regularExpression: ^(?:[a-z0-9][a-z0-9-]{2,62}[a-z0-9](?:,[a-z0-9][a-z0-9-]{2,62}[a-z0-9])*?)$
              errorMessage: The field should only contain lowercase letters, numbers, and hyphens, and must begin with a letter or a number. Each hyphen must be preceded and followed by a non-hyphen character. The name must also be between 3 and 63 characters long.
        performance:
          title: Performance
          type: string
          description: |
            Not editable. Determine whether you want to have premium performance for block blobs, file shares, or page blobs in your storage account.
          default: Standard
          enum:
            - Premium
            - Standard
          enumNames:
            - Premium (Recommended for scenarios that required low latency)
            - Standard (Recommended for most scenarios (general-purpose v2 account))
          ui:disabled: true
        redundancy:
          title: Redundancy
          type: string
          description: |
            Not editable. The data in your Azure storage account is always replicated to ensure durability and high availability.
            Choose a replication strategy that matches your durability requirements.
          default: LRS
          enum:
            - LRS
            - GRS
            - ZRS
            - GZRS
          enumNames:
            - "LRS: Lowest-cost option with basic protection against server rack and drive failures. Recommended for non-critical scenarios."
            - "GRS: Intermediate option with failover capabilities in a secondary region. Recommended for backup scenarios."
            - "ZRS: Intermediate option with protection against datacenter-level failures. Recommended for high availability scenarios."
            - "GZRS: Optimal data protection solution that includes the offerings of both GRS and ZRS. Recommended for critical data scenarios."
          ui:disabled: true
        accessTier:
          title: Access Tier
          type: object
          description: |
            Not Editable. The account access tier is the default tier that is inferred by any blob without an explicitly set tier.
          properties:
            customRadio:
              type: string
              title: Choose an Access Tier
              default: Hot
              ui:widget: radio
              ui:disabled: true
              oneOf:
                - const: Hot
                  title: "Hot: Optimized for frequently accessed data and everyday usage scenarios"
                - const: Cold
                  title: "Cold: Optimized for infrequently accessed data and backup scenarios"
        infrastructureEncryptionEnabled:
          title: Enable Infrastructure Encryption
          type: boolean
          default: false
          ui:disabled: true
          description: Not Editable. By default, Azure encrypts storage account data at rest. By enabling it, infrastructure encryption adds a second layer of encryption to your storage account's data.
        allowNestedItemsToBePublic:
          title: Allow Nested Items to be Public
          type: boolean
          default: true
          description: Allow or disallow nested items within this Account to opt into being public. Defaults to true.

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./edit-skeleton
        targetPath: '.'
        values:
          fullyQualifiedName: '${{ parameters.fullyQualifiedName }}'
          description: '${{ parameters.description }}'
          identifier: '${{ parameters.identifier }}'
          developmentGroup: '${{ parameters.developmentGroup }}'
          dependsOn: '${{ parameters.dependsOn }}'
          tags: '${{ parameters.tags }}'
          containers: '${{ parameters.containers }}'
          allowNestedItemsToBePublic: '${{ parameters.allowNestedItemsToBePublic }}'