{% set domainNameNormalized = values.domain | replace(r/domain:| |-/, "") %}
{% set dataProductNameNormalized = values.dataproduct.split(".")[1] | replace(r/ |-/g, "") %}
{% set dataProductMajorVersion = values.identifier.split(".")[2] %}
{% set componentNameNormalized = values.name.split(" ") | join("") | lower %}

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.identifier }}
  description: |
        "${{ values.description }}"
  annotations:
    gitlab.com/project-slug: 'AgileDMBSandbox/${{orgname}}/mesh.repository/${{ domainNameNormalized }}/${{ dataProductNameNormalized }}/${{ componentNameNormalized }}'
    backstage.io/techdocs-ref: dir:.
  links:
    - url: ${{ "https://"+ values.storageAccount +".blob.core.windows.net/" }}
      title: Azure Storage Account with ADLSgen2 container
      icon: cloud
  tags:
    - azure
    - adlsgen2
    - storage
spec:
  type: storage
  lifecycle: experimental
  owner: ${{ values.developmentGroup }}
  system: ${{ values.dataproduct }}
  domain: ${{ values.domain }}
  mesh:
    name: ${{ values.name }}
    fullyQualifiedName: ${{ values.fullyQualifiedName }}
    description: | 
          "${{ values.description }}"
    kind: storage
    version: ${{ values.identifier.split(".")[2] + ".0.0" }}
    infrastructureTemplateId: ${{ values.infrastructureTemplateId }}
    useCaseTemplateId: ${{ values.useCaseTemplateId }}
    dependsOn: {% if values.dependsOn | length > 0 %}{% for i in values.dependsOn %}
      - ${{ i }}{% endfor %}{% else %}[]{% endif %}
    platform: Azure
    technology: ADLSgen2
    tags: {% if values.tags | length > 0 %}{% for i in values.tags %}
      - tagFQN: ${{ i }}
        source: Tag
        labelType: Manual
        state: Confirmed{% endfor %}{% else %}[]{% endif %}
    specific:
      component:
        dpDomain: ${{ domainNameNormalized }}
        dpNameMajorVersion: ${{ dataProductNameNormalized + "_" + dataProductMajorVersion }}
        name: ${{ componentNameNormalized }}
      resourceGroup: ${{ values.resourceGroup }}
      storageAccount: ${{ values.storageAccount }}
      containers: {% if values.containers | length > 0 %}${{ values.containers | join(",") }}{% else %}''{% endif %}
      performance: ${{ values.performance }}
      redundancy: ${{ values.redundancy }}
      accessTier: ${{ values.accessTier }}
      infrastructureEncryptionEnabled: ${{ values.infrastructureEncryptionEnabled }}
      allowNestedItemsToBePublic: ${{ values.allowNestedItemsToBePublic }}
      state:
        key: ${{ domainNameNormalized + "_" + dataProductNameNormalized + "_" + dataProductMajorVersion + "_" + componentNameNormalized + ".tfstate" }}
